Repository eclipse-tractusx/sldt-semantic-models, pull requests merged in 2023-02, with the labels that each got.

#48 BOMAsSpecified technical committee feedback
  io.catenax.bom_as_specified/1.0.1/BomAsSpecified.ttl
  io.catenax.bom_as_specified/1.0.1/metadata.json
  io.catenax.bom_as_specified/RELEASE_NOTES.md
Labels: MS2-Approved, MS3-Approved

#66 RemanufacturingCertificate reopen PR due to ECA failure
  io.catenax.remanufacturing_certificate/1.0.0/RemanufacturingCertificate.ttl
  io.catenax.remanufacturing_certificate/1.0.0/metadata.json
  io.catenax.remanufacturing_certificate/RELEASE_NOTES.md
Labels: MS2-Approved, MS3-Approved

#65 ReturnRequest reopen PR due to ECA failure
  io.catenax.return_request/1.1.2/ReturnRequest.ttl
  io.catenax.return_request/1.1.2/metadata.json
  io.catenax.return_request/RELEASE_NOTES.md
Labels: MS2-Approved, MS3-Approved

#63 ReuseCertificate reopen PR due to ECA failure
  io.catenax.reuse_certificate/1.0.0/ReuseCertificate.ttl
  io.catenax.reuse_certificate/1.0.0/metadata.json
  io.catenax.reuse_certificate/RELEASE_NOTES.md
Labels: MS2-Approved, MS3-Approved

#62 RefurbishingCertificate reopen PR due to ECA failure
  io.catenax.refurbishing_certificate/1.0.0/RefurbishingCertificate.ttl
  io.catenax.refurbishing_certificate/1.0.0/metadata.json
  io.catenax.refurbishing_certificate/RELEASE_NOTES.md
Labels: MS2-Approved, MS3-Approved

#61 PartAsSpecified reopen PR due to ECA failure
  io.catenax.part_as_specified/1.0.1/PartAsSpecified.ttl
  io.catenax.part_as_specified/1.0.1/metadata.json
  io.catenax.part_as_specified/RELEASE_NOTES.md
Labels: MS2-Approved, MS3-Approved

#69 [New model]: initial model of decomissioning certificate
  io.catenax.decomissioning_certificate/1.0.0/DecommissioningCertificate.ttl
  io.catenax.decomissioning_certificate/1.0.0/metadata.json
  io.catenax.decomissioning_certificate/RELEASE_NOTES.md
Labels: MS3-Approved

#68 [Model Update]: BatteryPass: several smaller fixes according to technical commitee feedback
  io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl
  io.catenax.battery.battery_pass/3.0.1/metadata.json
  io.catenax.battery.battery_pass/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved
