Repository eclipse-tractusx/sldt-semantic-models, pull requests merged in 2024-01, with the labels that each got.

#454 [Model Deprecation]: PartSiteInformationAsPlanned 1.0.0
  io.catenax.part_site_information_as_planned/1.0.0/metadata.json
Labels: MS3_Approved

#501 [Model Deprecation]: SerialPart 1.0.1
  io.catenax.serial_part/1.0.1/metadata.json
Labels: MS3_Approved

#503 [Model Deprecation]: Batch 2.0.0
  io.catenax.batch/2.0.0/metadata.json
Labels: MS3_Approved

#505 [Model Deprecation]: JustInSequencePart 1.0.0
  io.catenax.just_in_sequence_part/1.0.0/metadata.json
Labels: MS3_Approved

#508 [Model Deprecation]: Shared MessageHeader 1.0.0
  io.catenax.shared.message_header/1.0.0/metadata.json
Labels: MS3_Approved

#510 [Model Deprecation]: SingleLevelBomAsBuilt 1.0.0
  io.catenax.single_level_bom_as_built/1.0.0/metadata.json
Labels: MS3_Approved

#515 Update: QualityTaks to 2.0.0
  io.catenax.quality_task/2.0.0/QualityTask.ttl
  io.catenax.quality_task/2.0.0/gen/QualityTask-schema.json
  io.catenax.quality_task/2.0.0/gen/QualityTask.html
  io.catenax.quality_task/2.0.0/gen/QualityTask.json
  io.catenax.quality_task/2.0.0/gen/QualityTask.png
  io.catenax.quality_task/2.0.0/metadata.json
  io.catenax.quality_task/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#514 Update: Fleet.Vehicles to 2.0.0
  io.catenax.fleet.vehicles/2.0.0/Vehicles.ttl
  io.catenax.fleet.vehicles/2.0.0/gen/Vehicles-schema.json
  io.catenax.fleet.vehicles/2.0.0/gen/Vehicles.html
  io.catenax.fleet.vehicles/2.0.0/gen/Vehicles.json
  io.catenax.fleet.vehicles/2.0.0/gen/Vehicles.png
  io.catenax.fleet.vehicles/2.0.0/metadata.json
  io.catenax.fleet.vehicles/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#516 Update PartsAnalyses to 3.0.0
  io.catenax.parts_analyses/3.0.0/PartsAnalyses.ttl
  io.catenax.parts_analyses/3.0.0/gen/PartsAnalyses-schema.json
  io.catenax.parts_analyses/3.0.0/gen/PartsAnalyses.html
  io.catenax.parts_analyses/3.0.0/gen/PartsAnalyses.json
  io.catenax.parts_analyses/3.0.0/gen/PartsAnalyses.png
  io.catenax.parts_analyses/3.0.0/metadata.json
  io.catenax.parts_analyses/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#521 [NEW MODEL]: PartClassification 1.0.0
  io.catenax.shared.part_classification/1.0.0/PartClassification.ttl
  io.catenax.shared.part_classification/1.0.0/metadata.json
  io.catenax.shared.part_classification/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#517 Update ManufacturedPartsQInformtaion to 2.0.0
  io.catenax.manufactured_parts_quality_information/2.0.0/ManufacturedPartsQualityInformation.ttl
  io.catenax.manufactured_parts_quality_information/2.0.0/gen/ManufacturedPartsQualityInformation-schema.json
  io.catenax.manufactured_parts_quality_information/2.0.0/gen/ManufacturedPartsQualityInformation.html
  io.catenax.manufactured_parts_quality_information/2.0.0/gen/ManufacturedPartsQualityInformation.json
  io.catenax.manufactured_parts_quality_information/2.0.0/gen/ManufacturedPartsQualityInformation.png
  io.catenax.manufactured_parts_quality_information/2.0.0/metadata.json
  io.catenax.manufactured_parts_quality_information/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#518 Update Fleet.DiagnosticData to 2.0.0
  io.catenax.fleet.diagnostic_data/2.0.0/DiagnosticData.ttl
  io.catenax.fleet.diagnostic_data/2.0.0/gen/DiagnosticData-sample.json
  io.catenax.fleet.diagnostic_data/2.0.0/gen/DiagnosticData-schema.json
  io.catenax.fleet.diagnostic_data/2.0.0/gen/DiagnosticData.html
  io.catenax.fleet.diagnostic_data/2.0.0/gen/DiagnosticData.png
  io.catenax.fleet.diagnostic_data/2.0.0/metadata.json
  io.catenax.fleet.diagnostic_data/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#519 Update Fleet.ClaimData to 2.0.0
  io.catenax.fleet.claim_data/2.0.0/ClaimData.ttl
  io.catenax.fleet.claim_data/2.0.0/gen/ClaimData-sample.json
  io.catenax.fleet.claim_data/2.0.0/gen/ClaimData-schema.json
  io.catenax.fleet.claim_data/2.0.0/gen/ClaimData.html
  io.catenax.fleet.claim_data/2.0.0/gen/ClaimData.png
  io.catenax.fleet.claim_data/2.0.0/metadata.json
  io.catenax.fleet.claim_data/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#551 [Model Update] shopfloor_information_types
  io.catenax.shared.shopfloor_information_types/1.0.0/ShopfloorInformationTypes.ttl
  io.catenax.shared.shopfloor_information_types/2.0.0/ShopfloorInformationTypes.ttl
  io.catenax.shared.shopfloor_information_types/2.0.0/metadata.json
  io.catenax.shared.shopfloor_information_types/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#553 [Model Update] Get production forecast 2.0.0
  io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
  io.catenax.shopfloor_information.get_production_forecast/2.0.0/GetProductionForecast.ttl
  io.catenax.shopfloor_information.get_production_forecast/2.0.0/metadata.json
  io.catenax.shopfloor_information.get_production_forecast/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#569 [New Model] Bill of process
  io.catenax.shared.bill_of_process/1.0.0/BillOfProcessSharedAspect.ttl
  io.catenax.shared.bill_of_process/1.0.0/README.md
  io.catenax.shared.bill_of_process/1.0.0/images/img.png
  io.catenax.shared.bill_of_process/1.0.0/images/img_1.png
  io.catenax.shared.bill_of_process/1.0.0/images/img_2.png
  io.catenax.shared.bill_of_process/1.0.0/images/img_3.png
  io.catenax.shared.bill_of_process/1.0.0/images/img_4.png
  io.catenax.shared.bill_of_process/1.0.0/images/img_5.png
  io.catenax.shared.bill_of_process/1.0.0/images/img_6.png
  io.catenax.shared.bill_of_process/1.0.0/metadata.json
  io.catenax.shared.bill_of_process/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#574 [Model Update] Manufacturing Capability 3.0.0
  io.catenax.manufacturing_capability/1.0.0/metadata.json
  io.catenax.manufacturing_capability/2.0.0/metadata.json
  io.catenax.manufacturing_capability/3.0.0/ManufacturingCapability.ttl
  io.catenax.manufacturing_capability/3.0.0/gen/ManufacturingCapability-sample.json
  io.catenax.manufacturing_capability/3.0.0/gen/ManufacturingCapability-schema.json
  io.catenax.manufacturing_capability/3.0.0/metadata.json
  io.catenax.manufacturing_capability/RELEASE_NOTES.md
Labels: MS2_Approved, MS3_Approved

#571 fix(BusinessPartnerNumber): adjusted regex to match CX-0010
  io.catenax.shared.business_partner_number/2.0.0/BusinessPartnerNumber.ttl
  io.catenax.shared.business_partner_number/2.0.0/metadata.json
  io.catenax.shared.business_partner_number/RELEASE_NOTES.md
Labels: MS2_Approved
